namespace Ziopuzzle.CustomButton;

// Only literal fallbacks whose explicit spelling preserves omission semantics.
// Leave inherited, theme-dependent and attribute-presence switches unspecified.
internal static class PropertyDefaults
{
    internal static string? Get(string type, string name) => name switch
    {
        "opacity" => "1",
        "visible" => "true",
        "interactive" or "disabled" or "showCursorWhileTouching" or "wrap" => "false",
        "transitionMs" => "0",
        "transitionProperties" => "opacity",
        "easing" => "ease-out",
        "colorSpace" => "linear-rgb",
        "transition" => "none",
        "direction" when type == "stack" => "vertical",
        "direction" when type == "slider" => "horizontal",
        "justify" when type == "stack" => "start",
        "align" when type == "stack" => "stretch",
        "align" when type == "dynamic-text" => "start",
        "padding" or "gap" => "0",
        "clip" => "none",
        "rotation" or "offsetX" or "offsetY" => "0",
        "originX" or "originY" => "0.5",
        "zoom" or "brightness" or "saturation" => "1",
        "fit" => "contain",
        "name" when type == "icon" => "star",
        "format" => "time",
        "seconds" => type == "clock" ? "true" : "false",
        "weight" => "regular",
        "maxLines" => "1",
        "size" when type is "text" or "dynamic-text" => "18%",
        "size" when type is "icon" or "toggle" => "20%",
        "size" when type is "image" or "svg" => "100%",
        "min" => "0",
        "max" => "100",
        "step" or "stepX" or "stepY" => "0",
        "keyX" => "x",
        "keyY" => "y",
        "leftValue" or "topValue" => "0",
        "rightValue" or "bottomValue" => "100",
        "background" when type == "trackpad" => "#252525",
        "color" when type is "gauge" or "bar" or "chart" or "progress-bar" or "slider" or "dial" or "toggle" or "segmented" or "trackpad" or "rect" or "circle" or "capsule" or "path" or "polygon" or "sector" or "line" => "#54dfcc",
        "thickness" when type is "dial" or "slider" or "gauge" => "4%",
        "thickness" when type is "bar" or "progress-bar" => "5%",
        "thickness" when type == "chart" => "1.5%",
        "thickness" when type == "line" => "2%",
        "points" when type == "chart" => "60",
        "points" when type == "polygon" => "10%,90%;50%,10%;90%,90%",
        "plotTop" => "66%",
        "rate" or "positionMs" => "0",
        "startAngle" when type is "gauge" or "dial" => "-135",
        "endAngle" when type is "gauge" or "dial" => "135",
        "startAngle" when type == "sector" => "-90",
        "sweepAngle" => "120",
        "cx" or "cy" when type == "sector" => "50%",
        "radius" => type == "sector" ? "40%" : "0",
        "coordinates" => "widget",
        "width" when type is "rect" or "circle" or "capsule" or "path" => "40%",
        "height" when type is "circle" or "path" => "40%",
        "height" when type is "rect" or "capsule" => "20%",
        "x" or "y" when type != "line" => "0",
        "data" => "M0 0 L1 0.5 L0 1 Z",
        "corner" => "square",
        "cornerRadius" => "6%",
        "strokeWidth" => "1%",
        "gradient" => "none",
        "gradientAngle" => "90",
        "gradientX" or "gradientY" => "50%",
        _ => null
    };
}
